### ISSUE TITLE
플러그인 실행중 오류가 발생합니다.

### ISSUE THREAD

**Issue by parksangwon** [OrigamiDream/homebridge-daelim-smarthome#1]
안녕하세요.
유용한 플러그인 만들어주셔서 감사합니다.
카페를 통해 알게되어 사용하던 중에 몇가지 문제가 발생해 이슈 남깁니다.

1. 실행중 outlet.ts에서 오류가 발생했는데, 확인 부탁드립니다.
```
[11/11/2021, 8:15:12 AM] [DaelimSmartHomePlatform] Connected to server
[11/11/2021, 8:15:12 AM] TypeError: Cannot read property 'length' of undefined
    at Object.callback (/homebridge/node_modules/homebridge-daelim-smarthome/homebridge/accessories/outlet.ts:121:40)
    at NetworkHandler.handleResponse (/homebridge/node_modules/homebridge-daelim-smarthome/core/network.ts:232:34)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-daelim-smarthome/core/network.ts:152:26)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
ERROR: uncaughtException: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Object.callback (/homebridge/node_modules/homebridge-daelim-smarthome/homebridge/accessories/outlet.ts:121:40)
    at NetworkHandler.handleResponse (/homebridge/node_modules/homebridge-daelim-smarthome/core/network.ts:232:34)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-daelim-smarthome/core/network.ts:152:26)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
[11/11/2021, 8:15:12 AM] Got SIGTERM, shutting down Homebridge...
```

2. 위 문제로 디버깅하고자 1.에서 설치한 플러그인을 제거 한 뒤,
[Terminal로 설치하는 방법](https://github.com/OrigamiDream/homebridge-daelim-smarthome#직접-빌드하여-terminal에서-설치)대로 git clone 후, 디버깅 코드를 추가, sudo npm link 명령어를 실행했는데 homebridge plugin에서 해당 플러그인을 불러오지 못했습니다.

혹시 npm link에 별도로 param을 주어야 하나요? sudo npm link만 실행했을 때는 `/usr/lib/node-modules/homebridge-daelim-smarthome`에 디렉토리가 생겨서 설치 방법에 누락된 부분이 있는지 궁금합니다.

**Comment by OrigamiDream** [comment]
거주하시는 아파트에 스마트 콘센트가 있는지 확인 한번 부탁드립니다.

2번의 경우 `sudo` 없이 `npm link` 만 실행해야합니다.

**Comment by parksangwon** [comment]
앱으로 제어할 수 있는 콘센트는 없습니다. 
조명, 난방, 가스, 엘리베이터콜 만 가능합니다.

**Comment by OrigamiDream** [comment]
수정사항이 배포되었습니다. 플러그인을 업데이트 받으실 수 있습니다.

커밋: c6acd5a33615e3e98450002ab44e45a4db6238d6

**Comment by parksangwon** [comment]
아파트마다 accessory 구성이 다른 것이 반영되었군요.
빠른 수정 감사합니다. :)
